/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentCapabilitiesRouteImport } from './routes/agent-capabilities'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as GlobalChatSessionsSessionIdRouteImport } from './routes/global-chat-sessions.$sessionId'
import { Route as GlobalChatSessionsNewRouteImport } from './routes/global-chat-sessions.new'
import { Route as ProjectSessionsSessionIdRouteImport } from './routes/project-sessions.$sessionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentCapabilitiesRoute = AgentCapabilitiesRouteImport.update({
  id: '/agent-capabilities',
  path: '/agent-capabilities',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const GlobalChatSessionsSessionIdRoute =
  GlobalChatSessionsSessionIdRouteImport.update({
    id: '/global-chat-sessions/$sessionId',
    path: '/global-chat-sessions/$sessionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const GlobalChatSessionsNewRoute = GlobalChatSessionsNewRouteImport.update({
  id: '/global-chat-sessions/new',
  path: '/global-chat-sessions/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectSessionsSessionIdRoute =
  ProjectSessionsSessionIdRouteImport.update({
    id: '/project-sessions/$sessionId',
    path: '/project-sessions/$sessionId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent-capabilities': typeof AgentCapabilitiesRoute
  '/settings': typeof SettingsRoute
  '/global-chat-sessions/$sessionId': typeof GlobalChatSessionsSessionIdRoute
  '/global-chat-sessions/new': typeof GlobalChatSessionsNewRoute
  '/project-sessions/$sessionId': typeof ProjectSessionsSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent-capabilities': typeof AgentCapabilitiesRoute
  '/settings': typeof SettingsRoute
  '/global-chat-sessions/$sessionId': typeof GlobalChatSessionsSessionIdRoute
  '/global-chat-sessions/new': typeof GlobalChatSessionsNewRoute
  '/project-sessions/$sessionId': typeof ProjectSessionsSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent-capabilities': typeof AgentCapabilitiesRoute
  '/settings': typeof SettingsRoute
  '/global-chat-sessions/$sessionId': typeof GlobalChatSessionsSessionIdRoute
  '/global-chat-sessions/new': typeof GlobalChatSessionsNewRoute
  '/project-sessions/$sessionId': typeof ProjectSessionsSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent-capabilities'
    | '/settings'
    | '/global-chat-sessions/$sessionId'
    | '/global-chat-sessions/new'
    | '/project-sessions/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent-capabilities'
    | '/settings'
    | '/global-chat-sessions/$sessionId'
    | '/global-chat-sessions/new'
    | '/project-sessions/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/agent-capabilities'
    | '/settings'
    | '/global-chat-sessions/$sessionId'
    | '/global-chat-sessions/new'
    | '/project-sessions/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentCapabilitiesRoute: typeof AgentCapabilitiesRoute
  SettingsRoute: typeof SettingsRoute
  GlobalChatSessionsSessionIdRoute: typeof GlobalChatSessionsSessionIdRoute
  GlobalChatSessionsNewRoute: typeof GlobalChatSessionsNewRoute
  ProjectSessionsSessionIdRoute: typeof ProjectSessionsSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-capabilities': {
      id: '/agent-capabilities'
      path: '/agent-capabilities'
      fullPath: '/agent-capabilities'
      preLoaderRoute: typeof AgentCapabilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/global-chat-sessions/$sessionId': {
      id: '/global-chat-sessions/$sessionId'
      path: '/global-chat-sessions/$sessionId'
      fullPath: '/global-chat-sessions/$sessionId'
      preLoaderRoute: typeof GlobalChatSessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/global-chat-sessions/new': {
      id: '/global-chat-sessions/new'
      path: '/global-chat-sessions/new'
      fullPath: '/global-chat-sessions/new'
      preLoaderRoute: typeof GlobalChatSessionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project-sessions/$sessionId': {
      id: '/project-sessions/$sessionId'
      path: '/project-sessions/$sessionId'
      fullPath: '/project-sessions/$sessionId'
      preLoaderRoute: typeof ProjectSessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentCapabilitiesRoute: AgentCapabilitiesRoute,
  SettingsRoute: SettingsRoute,
  GlobalChatSessionsSessionIdRoute: GlobalChatSessionsSessionIdRoute,
  GlobalChatSessionsNewRoute: GlobalChatSessionsNewRoute,
  ProjectSessionsSessionIdRoute: ProjectSessionsSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
