const SIDEBAR_DEFAULT_WIDTH = 280
const SIDEBAR_RIGHT_DEFAULT_WIDTH = 320
const SIDEBAR_MIN_WIDTH = 280
const SIDEBAR_MAX_WIDTH = 520
const SIDEBAR_KEYBOARD_RESIZE_STEP = 24

function clampSidebarWidth(width: number): number {
  return Math.min(SIDEBAR_MAX_WIDTH, Math.max(SIDEBAR_MIN_WIDTH, width))
}

export {
  SIDEBAR_DEFAULT_WIDTH,
  SIDEBAR_KEYBOARD_RESIZE_STEP,
  SIDEBAR_MAX_WIDTH,
  SIDEBAR_MIN_WIDTH,
  SIDEBAR_RIGHT_DEFAULT_WIDTH,
  clampSidebarWidth
}
