const MONACO_LANGUAGE_BY_FILENAME = new Map<string, string>([
  ['.editorconfig', 'ini'],
  ['.gitattributes', 'ini'],
  ['.gitconfig', 'ini'],
  ['config', 'ini'],
  ['dockerfile', 'dockerfile'],
  ['gemfile', 'ruby'],
  ['jakefile', 'javascript'],
  ['rakefile', 'ruby']
])

const MONACO_LANGUAGE_BY_EXTENSION = new Map<string, string>([
  ['abap', 'abap'],
  ['aes', 'aes'],
  ['ascx', 'xml'],
  ['asp', 'html'],
  ['aspx', 'html'],
  ['azcli', 'azcli'],
  ['babelrc', 'json'],
  ['bash', 'shell'],
  ['bat', 'bat'],
  ['bicep', 'bicep'],
  ['bowerrc', 'json'],
  ['c', 'c'],
  ['cc', 'cpp'],
  ['cake', 'csharp'],
  ['cjs', 'javascript'],
  ['clj', 'clojure'],
  ['cljc', 'clojure'],
  ['cljs', 'clojure'],
  ['cls', 'apex'],
  ['cmd', 'bat'],
  ['cxx', 'cpp'],
  ['coffee', 'coffeescript'],
  ['config', 'xml'],
  ['cpy', 'python'],
  ['cs', 'csharp'],
  ['cshtml', 'razor'],
  ['cpp', 'cpp'],
  ['csp', 'csp'],
  ['csproj', 'xml'],
  ['css', 'css'],
  ['csx', 'csharp'],
  ['ctp', 'php'],
  ['cts', 'typescript'],
  ['cyp', 'cypher'],
  ['cypher', 'cypher'],
  ['dart', 'dart'],
  ['dats', 'postiats'],
  ['dax', 'msdax'],
  ['dockerfile', 'dockerfile'],
  ['dtd', 'xml'],
  ['ecl', 'ecl'],
  ['edn', 'clojure'],
  ['es6', 'javascript'],
  ['eslintrc', 'json'],
  ['ex', 'elixir'],
  ['exs', 'elixir'],
  ['flow', 'flow9'],
  ['fs', 'fsharp'],
  ['fsi', 'fsharp'],
  ['fsscript', 'fsharp'],
  ['fsx', 'fsharp'],
  ['ftl', 'freemarker2'],
  ['ftlh', 'freemarker2'],
  ['ftlx', 'freemarker2'],
  ['gemspec', 'ruby'],
  ['gitconfig', 'ini'],
  ['go', 'go'],
  ['gql', 'graphql'],
  ['graphql', 'graphql'],
  ['gyp', 'python'],
  ['gypi', 'python'],
  ['h', 'c'],
  ['hh', 'cpp'],
  ['hpp', 'cpp'],
  ['hxx', 'cpp'],
  ['handlebars', 'handlebars'],
  ['har', 'json'],
  ['hats', 'postiats'],
  ['hbs', 'handlebars'],
  ['hcl', 'hcl'],
  ['htm', 'html'],
  ['html', 'html'],
  ['html.liquid', 'liquid'],
  ['i3', 'm3'],
  ['iecplc', 'st'],
  ['iecst', 'st'],
  ['ig', 'm3'],
  ['ini', 'ini'],
  ['jade', 'pug'],
  ['jav', 'java'],
  ['java', 'java'],
  ['jl', 'julia'],
  ['js', 'javascript'],
  ['jscsrc', 'json'],
  ['jshintrc', 'json'],
  ['jshtm', 'html'],
  ['json', 'json'],
  ['jsp', 'html'],
  ['jsx', 'javascript'],
  ['kt', 'kotlin'],
  ['kts', 'kotlin'],
  ['lc3lib', 'st'],
  ['less', 'less'],
  ['lex', 'lexon'],
  ['ligo', 'pascaligo'],
  ['liquid', 'liquid'],
  ['lua', 'lua'],
  ['m', 'objective-c'],
  ['m3', 'm3'],
  ['markdown', 'markdown'],
  ['md', 'markdown'],
  ['mdoc', 'html'],
  ['mdown', 'markdown'],
  ['mdtext', 'markdown'],
  ['mdtxt', 'markdown'],
  ['mdwn', 'markdown'],
  ['mdx', 'mdx'],
  ['mg', 'm3'],
  ['mjs', 'javascript'],
  ['mkd', 'markdown'],
  ['mkdn', 'markdown'],
  ['ml', 'fsharp'],
  ['mli', 'fsharp'],
  ['mligo', 'cameligo'],
  ['msdax', 'msdax'],
  ['mts', 'typescript'],
  ['opf', 'xml'],
  ['p', 'pascal'],
  ['pas', 'pascal'],
  ['php', 'php'],
  ['php4', 'php'],
  ['php5', 'php'],
  ['phtml', 'php'],
  ['pl', 'perl'],
  ['pla', 'pla'],
  ['pm', 'perl'],
  ['pp', 'pascal'],
  ['pq', 'powerquery'],
  ['pqm', 'powerquery'],
  ['properties', 'ini'],
  ['props', 'xml'],
  ['proto', 'proto'],
  ['ps1', 'powershell'],
  ['psd1', 'powershell'],
  ['psm1', 'powershell'],
  ['pug', 'pug'],
  ['py', 'python'],
  ['pyw', 'python'],
  ['qs', 'qsharp'],
  ['r', 'r'],
  ['rb', 'ruby'],
  ['rbx', 'ruby'],
  ['redis', 'redis'],
  ['rhistory', 'r'],
  ['rjs', 'ruby'],
  ['rkt', 'scheme'],
  ['rlib', 'rust'],
  ['rmd', 'r'],
  ['rprofile', 'r'],
  ['rpy', 'python'],
  ['rq', 'sparql'],
  ['rs', 'rust'],
  ['rst', 'restructuredtext'],
  ['rt', 'r'],
  ['s', 'mips'],
  ['sats', 'postiats'],
  ['sb', 'sb'],
  ['sbt', 'scala'],
  ['sc', 'scala'],
  ['scala', 'scala'],
  ['sch', 'scheme'],
  ['scm', 'scheme'],
  ['scss', 'scss'],
  ['sh', 'shell'],
  ['shtml', 'html'],
  ['sol', 'sol'],
  ['sql', 'sql'],
  ['ss', 'scheme'],
  ['st', 'st'],
  ['sv', 'systemverilog'],
  ['svg', 'xml'],
  ['svgz', 'xml'],
  ['svh', 'systemverilog'],
  ['swift', 'swift'],
  ['targets', 'xml'],
  ['tcdut', 'st'],
  ['tcgvl', 'st'],
  ['tcio', 'st'],
  ['tcl', 'tcl'],
  ['tcpou', 'st'],
  ['tf', 'hcl'],
  ['tfvars', 'hcl'],
  ['ts', 'typescript'],
  ['tsp', 'typespec'],
  ['tsx', 'typescript'],
  ['twig', 'twig'],
  ['v', 'verilog'],
  ['vb', 'vb'],
  ['vh', 'verilog'],
  ['wgsl', 'wgsl'],
  ['wxi', 'xml'],
  ['wxl', 'xml'],
  ['wxs', 'xml'],
  ['xaml', 'xml'],
  ['xhtml', 'html'],
  ['xml', 'xml'],
  ['xsd', 'xml'],
  ['xsl', 'xml'],
  ['xslt', 'xml'],
  ['yaml', 'yaml'],
  ['yml', 'yaml']
])

export function getFilesEditorLanguage(relativePath: string): string {
  const name = relativePath.split('/').at(-1) ?? relativePath
  const lowerName = name.toLowerCase()
  const filenameLanguage = MONACO_LANGUAGE_BY_FILENAME.get(lowerName)
  if (filenameLanguage) return filenameLanguage

  const extensionLanguage = getExtensions(lowerName)
    .map((extension) => MONACO_LANGUAGE_BY_EXTENSION.get(extension))
    .find((language): language is string => Boolean(language))
  return extensionLanguage ?? 'plaintext'
}

export function createFilesMonacoModelPath(sessionId: string, relativePath: string): string {
  const encodedSession = encodeURIComponent(sessionId)
  const encodedPath = relativePath
    .split('/')
    .map((segment) => encodeURIComponent(segment))
    .join('/')
  return `spacezero-files://${encodedSession}/${encodedPath}`
}

function getExtensions(lowerName: string): string[] {
  const parts = lowerName.split('.')
  if (parts.length <= 1) return []
  return parts.slice(1).map((_, index) => parts.slice(index + 1).join('.'))
}
